### ISSUE TITLE
Cannot calculate after equating

### ISSUE THREAD

**Issue by arch1824** [arch10/Calculator#7]
**Describe the bug**
If the equal sign '=' is pressed, the answer gets displayed to the input EditText. But when the operator is pressed after that, it ignores that operator.

**To Reproduce**
1. Write 5+5 and press '='
2. The main screen will now have 10
3. Press any operator or number after that. It will ignore the number in the main screen.

**Expected behavior**
After pressing the equal '=' sign the answer is transferred to main input screen. After which if any operator is clicked, the operator should be added after that. and the equation should be evaluated.

If any number is clicked after that, the screen should be cleared and the new number should be added to the screen.

**Screenshots**
NA

**Android (please complete the following information):**
 - Device: Redmi Note 3
 - OS: Android Nougat 7.1.2
 - App Version: 1.5.0

**Additional context**
NA

**Comment by arch10** [comment]
The is issue is resolved in the new branch. Will merge with the main branch soon after some testing.
